### PR TITLE
Big Schema + Auth

### PR DESCRIPTION
**Pull request by JoeNeedham**

### CODE REVIEW

**Comment by RichardZhang01** [comment]
Looks good Joe, just need to resolve the merge conflicts because this branch has deviated from dev. Should be fairly simple to diagnose, but let us know if you need help

May want to rename bigschema back to schema though, not a big deal, just convention would be to name the schema, schema

**Comment by JoeNeedham** [comment]
> Looks good Joe, just need to resolve the merge conflicts because this branch has deviated from dev. Should be fairly simple to diagnose, but let us know if you need help
> 
> May want to rename bigschema back to schema though, not a big deal, just convention would be to name the schema, schema

I will change bigschema back to schema. Unsure how to fix merge conflicts tbh. The settings.py was changed to point to the new schema. The receipts folder that the other conflict points to doesn't exist anymore on my branch.

**Comment by RichardZhang01** [comment]
> > Looks good Joe, just need to resolve the merge conflicts because this branch has deviated from dev. Should be fairly simple to diagnose, but let us know if you need help
> > May want to rename bigschema back to schema though, not a big deal, just convention would be to name the schema, schema
> 
> I will change bigschema back to schema. Unsure how to fix merge conflicts tbh. The settings.py was changed to point to the new schema. The receipts folder that the other conflict points to doesn't exist anymore on my branch.

We can look it over together if you'd like. But if you wanted to try it yourself, click the 'Use the command line' link in this PR, where it lists: Review required... All checks have passed... and directly under This branch has conflicts that must be solved to get started.

**Review by RichardZhang01 — APPROVED** [review]
Looks like you got the conflicts solved, nice work!

**Pull request merged**
