### PR TITLE
Create Receipt Page and Form UI

### PR DESCRIPTION
**Pull request by TiciaD**
- Added CreateReceiptForm component and page at '/create-receipt'
  - Added queries for AllTags and AllExpenseOptions
  - Added expenses query to backend graphql schema
  - Added mutation for CreateReceipt
  - Updated Navbar to have a link to route to `/create-receipt` page

### CODE REVIEW

**Comment by TiciaD** [comment]
@RichardZhang01 I think there is an issue with the way the backend is handling Decimals, if we pass it a decimal that's greater than 0.99 for the `tax`, it won't accept it otherwise the mutation works fine. Left this PR as a draft so we can look into it later but everything else should be ready for review

**Comment by RichardZhang01** [comment]
> @RichardZhang01 I think there is an issue with the way the backend is handling Decimals, if we pass it a decimal that's greater than 0.99 for the `tax`, it won't accept it otherwise the mutation works fine. Left this PR as a draft so we can look into it later but everything else should be ready for review

@TiciaD That was set up intentionally because I thought that tax wouldn't go above 99%. Do you think it would be better to not limit it?

**Comment by TiciaD** [comment]
> > @RichardZhang01 I think there is an issue with the way the backend is handling Decimals, if we pass it a decimal that's greater than 0.99 for the `tax`, it won't accept it otherwise the mutation works fine. Left this PR as a draft so we can look into it later but everything else should be ready for review
> 
> @TiciaD That was set up intentionally because I thought that tax wouldn't go above 99%. Do you think it would be better to not limit it?

Oh wait I think I'm confused on what we were doing with the tax field. So it's supposed to represent a percentage? I thought it was supposed to represent the dollar amount you're taxed. Like on your receipt it'd break it down and say your subtotal is $30.00, your tax is $2.00, and your total is $32.00.

**Comment by RichardZhang01** [comment]
> > > @RichardZhang01 I think there is an issue with the way the backend is handling Decimals, if we pass it a decimal that's greater than 0.99 for the `tax`, it won't accept it otherwise the mutation works fine. Left this PR as a draft so we can look into it later but everything else should be ready for review
> > 
> > 
> > @TiciaD That was set up intentionally because I thought that tax wouldn't go above 99%. Do you think it would be better to not limit it?
> 
> Oh wait I think I'm confused on what we were doing with the tax field. So it's supposed to represent a percentage? I thought it was supposed to represent the dollar amount you're taxed. Like on your receipt it'd break it down and say your subtotal is $30.00, your tax is $2.00, and your total is $32.00.

Ah. Definitely a misunderstanding then. We can change it so it's like how you were imagining it. Would that mean we would change cost to be like a subtotal? Or would it be a total cost? should we include new fields for subtotal and total to differentiate, or just use an algorithm to calculate one or the other based on the cost and tax?

**Comment by TiciaD** [comment]
> > > > @RichardZhang01 I think there is an issue with the way the backend is handling Decimals, if we pass it a decimal that's greater than 0.99 for the `tax`, it won't accept it otherwise the mutation works fine. Left this PR as a draft so we can look into it later but everything else should be ready for review
> > > 
> > > 
> > > @TiciaD That was set up intentionally because I thought that tax wouldn't go above 99%. Do you think it would be better to not limit it?
> > 
> > 
> > Oh wait I think I'm confused on what we were doing with the tax field. So it's supposed to represent a percentage? I thought it was supposed to represent the dollar amount you're taxed. Like on your receipt it'd break it down and say your subtotal is $30.00, your tax is $2.00, and your total is $32.00.
> 
> Ah. Definitely a misunderstanding then. We can change it so it's like how you were imagining it. Would that mean we would change cost to be like a subtotal? Or would it be a total cost? should we include new fields for subtotal and total to differentiate, or just use an algorithm to calculate one or the other based on the cost and tax?

I think we're fine with just the cost field representing total. I'd just make tax represent the dollar amount instead of the percentage of the total

**Comment by RichardZhang01** [comment]
> > > > > @RichardZhang01 I think there is an issue with the way the backend is handling Decimals, if we pass it a decimal that's greater than 0.99 for the `tax`, it won't accept it otherwise the mutation works fine. Left this PR as a draft so we can look into it later but everything else should be ready for review
> > > > 
> > > > 
> > > > @TiciaD That was set up intentionally because I thought that tax wouldn't go above 99%. Do you think it would be better to not limit it?
> > > 
> > > 
> > > Oh wait I think I'm confused on what we were doing with the tax field. So it's supposed to represent a percentage? I thought it was supposed to represent the dollar amount you're taxed. Like on your receipt it'd break it down and say your subtotal is $30.00, your tax is $2.00, and your total is $32.00.
> > 
> > 
> > Ah. Definitely a misunderstanding then. We can change it so it's like how you were imagining it. Would that mean we would change cost to be like a subtotal? Or would it be a total cost? should we include new fields for subtotal and total to differentiate, or just use an algorithm to calculate one or the other based on the cost and tax?
> 
> I think we're fine with just the cost field representing total. I'd just make tax represent the dollar amount instead of the percentage of the total

That makes sense. I updated my data-table branch with this change so the backend allows the same values as the cost field does currently, and the table now has tax as dollar amounts. I also added a subtotal column to the data table. It's up for PR now.

**Review by RichardZhang01 — APPROVED** [review]

**Pull request merged**
