### PR TITLE
Login Form UI

### PR DESCRIPTION
**Pull request by TiciaD**
- Added Login page and LoginForm component
    - Added link to Login page from Home page
    - Added material-icons package

Notes for testing:
- You'll want to run `npm install` before testing this since I had to add a package for `material-icons`
- Login button should link to `/login` page
- No form validation incorporated yet
- Not hooked up to the backend yet so submission function just runs a console.log()

### CODE REVIEW

**Comment by TiciaD** [comment]
Just realized I put username, not email for the first field so I'll go back in and have that fixed at some point tonight then it'll be ready for review lol. Create Account page should be up not long after!

**Comment by TiciaD** [comment]
Fixed the username field and changed it to Email, should be ready for review now!

**Review by RichardZhang01 — APPROVED** [review]
Looks good Ticia. Login button redirects to login form. Both fields functioning as intended. Password hide toggle works as intended. Login button logs 'submitted' to the console.

May want to add some styles that target different screen sizes, for example, dynamically sized text. Also, is there a way to change the background color for auto-filled fields? When I select a previously used email, for example, I get a gray background that clashes with the other colors. Not a big deal though

image

Nice work

**Comment by TiciaD** [comment]
@RichardZhang01 Was able to fix the autofill background color issue and get the dark mode to work properly with preferred system preferences. 

I'm not sure yet but the responsive typography might be a little tricky, from first glance it looks like we'd have to assign a scale for each html font tag for each breakpoint. I'll have to do some more research to see if there's an easier way to go about it but for now I'm just going to address that in a separate ticket so this ticket doesn't get to big!

**Pull request merged**
